version: "3.8"

services:
  next-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: next-app
    expose:
      - "3000"
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - next-app
